# Generated by Django 2.2.2 on 2019-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('love', 'love'), ('like', 'like'), ('wow', 'wow'), ('haha', 'haha'), ('sad', 'sad'), ('angry', 'angry')], max_length=5),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction',
            field=models.CharField(choices=[('love', 'love'), ('like', 'like'), ('wow', 'wow'), ('haha', 'haha'), ('sad', 'sad'), ('angry', 'angry')], max_length=5),
        ),
    ]
